FROM public.ecr.aws/lambda/python:3.8

# BUILD IMAGE: sudo docker build -t thumbnailer:local -f Dockerfile.local .

COPY app.py requirements.txt ./

RUN python3.8 -m pip install -r requirements.txt && \
    pip install --upgrade awscli

# Command can be overwritten by providing a different command in the template directly.
#CMD ["app.lambda_handler"]
ENTRYPOINT [ "/bin/bash" ]
