openapi: 3.0.3
info:
  title: Presign and Search API
  description: > 
    OpenAPI v3 documentation for ltd.noooner.dam.core APIs.
    Currently split across 2 endpoint URLS (see servers block for details)
  contact:
    name: Jussi Heinonen
    email: jussi.heinonen@noooner.ltd
  version: '0.0.2'
servers:
  - url: https://tm7do0vu9j.execute-api.eu-west-1.amazonaws.com
    description: Presign endpoint Base URL
  - url: https://yibz2ntz2d.execute-api.eu-west-1.amazonaws.com
    description: Search endpoint Base URL

paths:
  /presign:
    get:
      summary: Returns an URL for downloading/uploading an object
      parameters:
        - in: query
          name: filename
          schema:
            type: string
          description: The filename to acquire download/upload link for. Example value elisa.jpg
        - in: query
          name: action
          schema:
            type: string
            enum: ['get_object', 'put_object']
        - in: query
          name: expiration
          required: false
          schema:
            type: integer
          description: Optional Presign URL validity period in seconds. Example value 300 for 5 minutes until URL expires.
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/PresignUrlResponse'
        '404':
          description: NOT FOUND
          content:
            'application/json':
              schema:
                type: string   
    post:
      summary: Returns an URL for downloading/uploading an object
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                filename:
                  type: string
                action:
                  type: string
                  enum: ['get_object', 'put_object']
                expiration:
                  type: integer
                  default: 300
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/PresignUrlResponse'
        '404':
          description: NOT FOUND
          content:
            'application/json':
              schema:
                type: string                

  /search:
    get:
      summary: Search objects by keywords
      parameters:
        - in: query
          name: q
          schema:
            type: string
          description: Specify keywords separated by + sign or whitespace. Example query /search?q=real+madrid+champions
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/SearchResponse'
        '404':
          description: NOT FOUND
          content:
            'application/json':
              schema:
                type: string                  

# Descriptions of common components
components:
  schemas:
    PresignUrlResponse:
      type: object
      properties:        
        response:
          type: string
          description: >
            Cryptographically signed URL providing time-limited permission to upload/download objects to/from S3 bucket
          example: https://s3.eu-west-1.amazonaws.com/ltd.noooner.dam.core.download/noooner.png?AWSAccessKeyId=AKIAVE5GOT0123456789&Signature=rw2PPivEeW%2Fo7CkqNKg6jqH1oWo%3D&Expires=1621080907
    SearchResponse:
      type: object
      properties:
        id:
          type: object
          description: Object id, md5sum of the original, used as a primary key in DynamoDB
          properties:
            get_download_url:
              type: string
              format: url
              description: URL of Presign API for requesting time-limited download URL for an image/object
              example: https://tm7do0vu9j.execute-api.eu-west-1.amazonaws.com/presign?filename=GettyImages-801871502.jpg&action=get_object
            headline:
              type: string
              description: Content of the field headline in IPTC metadata
              example: "Views Of The Remains Of The Grenfell Tower Block"
            upload_time:
              type: string
              format: date-time
              description: Date and time when image was uploaded to the system
              example: "2021-04-20 13:19:06"
            thumbnail_url:
              type: string
              format: url
              description: URL to preview image (small size) to display with search result
              example: https://s3-eu-west-1.amazonaws.com/ltd.noooner.dam.core.thumbnails/00000000000000000000000000000000.jpg
            matching_keywords:
              type: array
              items:
                type: string
              description: Keyword used in search that matches the image metadata
              example: [ "real", "madrid" ]
            relevance:
              type: integer
              description: Relevance score. Higher number is considered more relevant than lower number.
              example: 2
