openapi: 3.0.3
info:
  title: Presign and Search API
  description: > 
    OpenAPI v3 documentation for ltd.noooner.dam.core APIs.
    Currently split across 2 endpoint URLS (see servers block for details)
  contact:
    name: Jussi Heinonen
    email: jussi.heinonen@noooner.ltd
  version: '0.0.2'
servers:
  - url: https://tm7do0vu9j.execute-api.eu-west-1.amazonaws.com
    description: Default endpoint, integrates with Presign, Search and Metadata endpoints

paths:
  /presign:
    get:
      summary: Returns an URL for downloading/uploading an object
      parameters:
        - in: query
          name: filename
          schema:
            type: string
          description: The filename to acquire download/upload link for. Example value elisa.jpg
        - in: query
          name: action
          schema:
            type: string
            enum: ['get_object', 'put_object']
        - in: query
          name: expiration
          required: false
          schema:
            type: integer
          description: Optional Presign URL validity period in seconds. Example value 300 for 5 minutes until URL expires.
      responses:
        '200':
          description: A time-limited URL to enable upload/download directly to S3 bucket
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/PresignUrlResponse'
        '404':
          description: NOT FOUND
          content:
            'application/json':
              schema:
                type: string   
    post:
      summary: Returns an URL for downloading/uploading an object
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                filename:
                  type: string
                action:
                  type: string
                  enum: ['get_object', 'put_object']
                expiration:
                  type: integer
                  default: 300
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/PresignUrlResponse'
        '404':
          description: NOT FOUND
          content:
            'application/json':
              schema:
                type: string                

  /search:
    get:
      summary: Search objects by keywords
      parameters:
        - in: query
          name: q
          schema:
            type: string
          description: Specify keywords separated by + sign or whitespace. Example query /search?q=real+madrid+champions
      responses:
        '200':
          description: Search results matching keywords
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/SearchResponse'
        '404':
          description: NOT FOUND
          content:
            'application/json':
              schema:
                type: string
  /metadata:
    get:
      summary: Get object metadata by ID
      parameters:
        - in: query
          name: id
          schema:
            type: string
          description: Get object metadata by ID. Example request /metadata?id=d7dcd8b8e2b35c19b42b81c6dfdc1280
      responses:
        '200':
          description: Metadata document in JSON format
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/MetadataResponse'
        '404':
          description: NOT FOUND
          content:
            'application/json':
              schema:
                type: string                                

# Descriptions of common components
components:
  schemas:
    PresignUrlResponse:
      type: object
      properties:        
        response:
          type: string
          description: >
            Cryptographically signed URL providing time-limited permission to upload/download objects to/from S3 bucket
          example: https://s3.eu-west-1.amazonaws.com/ltd.noooner.dam.core.download/noooner.png?AWSAccessKeyId=AKIAVE5GOT0123456789&Signature=rw2PPivEeW%2Fo7CkqNKg6jqH1oWo%3D&Expires=1621080907
    SearchResponse:
      type: object
      properties:
        id:
          type: object
          description: Object id, md5sum of the original, used as a primary key in DynamoDB
          properties:
            get_download_url:
              type: string
              format: url
              description: >
                URL for Presign API to request time-limited download URL for an image/object
                When firing a request as seen in the example field below, the API returns an URL similar to
                https://s3.eu-west-1.amazonaws.com/ltd.noooner.dam.core.download/GettyImages-801871502.jpg?AWSAccessKeyId=AKIAVE5GOT0123456789&Signature=rw2PPivEeW%2Fo7CkqNKg6jqH1oWo%3D&Expires=1621080907
                Presign URL received in response can be used to download the original image
              example: https://tm7do0vu9j.execute-api.eu-west-1.amazonaws.com/presign?filename=GettyImages-801871502.jpg&action=get_object
            headline:
              type: string
              description: Content of the field headline in IPTC metadata
              example: "Views Of The Remains Of The Grenfell Tower Block"
            upload_time:
              type: string
              format: date-time
              description: Date and time when image was uploaded to the system
              example: "2021-04-20 13:19:06"
            thumbnail_url:
              type: stringft.com/
              format: url
              description: URL to preview image (small size) to display with search result
              example: https://s3-eu-west-1.amazonaws.com/ltd.noooner.dam.core.thumbnails/00000000000000000000000000000000.jpg
            matching_keywords:
              type: array
              items:
                type: string
              description: Keyword used in search that matches the image metadata
              example: [ "real", "madrid" ]
            relevance:
              type: integer
              description: Relevance score. Higher number is considered more relevant than lower number.
              example: 2
    MetadataResponse:
      type: object
      properties:        
        id:
          type: string
          description: MD5 checksum of an object. Used as a primary key in the database
          example: 520a1db1df5614bc9f8d89ab42a32561
        md5:
          type: string
          description: equivalent to id property
        n_search:
          type: array
          description: A list of searchable keywords associated with the object
          example: ["football", "soccer"]
        original_filename:
          type: string
          description: Name of the object in the persistent storage
          example: train02.jpg
        thumbnail_url:
          type: string
          format: url
          description: Address of the thumbnail object
          example: https://s3-eu-west-1.amazonaws.com/ltd.noooner.dam.core.thumbnail.ltd-noooner-thumbdev/520a1db1df5614bc9f8d89ab42a32561.jpg
        upload_time:
          type: integer
          description: EPOCH timestamp for upload time
          example: 1621955355
        caption/abstract:
          type: string
          description: IPTC field for description of the object
        headline:
          type: string
          description: IPTC field for headline
      required:
        - id
        - md5
        - n_search
        - original_filename
        - thumbnail_url
        - upload_time

